"""empty message

Revision ID: 28cb142c2a5a
Revises: ae7ab1f7719a
Create Date: 2021-05-04 20:52:17.197129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cb142c2a5a'
down_revision = 'ae7ab1f7719a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulxes', sa.Column('anosEXP', sa.Integer(), nullable=False))
    op.drop_column('pulxes', 'añosEXP')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulxes', sa.Column('añosEXP', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('pulxes', 'anosEXP')
    # ### end Alembic commands ###
