"""empty message

Revision ID: 4622fe6a8418
Revises: 28cb142c2a5a
Create Date: 2021-05-05 01:16:45.102136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4622fe6a8418'
down_revision = '28cb142c2a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulxes', sa.Column('añosEXP', sa.Integer(), nullable=False))
    op.drop_column('pulxes', 'anosEXP')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulxes', sa.Column('anosEXP', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('pulxes', 'añosEXP')
    # ### end Alembic commands ###
