"""empty message

Revision ID: 592a3f321b08
Revises: 
Create Date: 2021-05-13 22:39:41.749505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592a3f321b08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pulxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('pulxe', sa.String(length=250), nullable=False),
    sa.Column('categoria', sa.String(length=250), nullable=False),
    sa.Column('canton', sa.String(length=250), nullable=False),
    sa.Column('distrito', sa.String(length=250), nullable=False),
    sa.Column('provincia', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('experiencia', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('calificacionPromedio', sa.Integer(), nullable=False),
    sa.Column('calificacionCantidad', sa.Integer(), nullable=False),
    sa.Column('calificacionTotal', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('mail', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcategorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcategorias')
    op.drop_table('user')
    op.drop_table('pulxes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
