"""empty message

Revision ID: 8be2a46f83b3
Revises: 264f15a1ba19
Create Date: 2021-05-02 03:00:44.948981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be2a46f83b3'
down_revision = '264f15a1ba19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('nombre_categoria', sa.String(length=250), nullable=False))
    op.drop_column('categorias', 'pulxe')
    op.drop_column('categorias', 'categoria')
    op.drop_column('categorias', 'canton')
    op.drop_column('categorias', 'hogar')
    op.drop_column('categorias', 'provincia')
    op.drop_column('categorias', 'distrito')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('distrito', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('categorias', sa.Column('provincia', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('categorias', sa.Column('hogar', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('categorias', sa.Column('canton', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('categorias', sa.Column('categoria', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('categorias', sa.Column('pulxe', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('categorias', 'nombre_categoria')
    # ### end Alembic commands ###
