"""empty message

Revision ID: ae7ab1f7719a
Revises: 8be2a46f83b3
Create Date: 2021-05-04 20:30:13.258587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7ab1f7719a'
down_revision = '8be2a46f83b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulxes', sa.Column('calificacionPromedio', sa.Integer(), nullable=False))
    op.add_column('pulxes', sa.Column('calificacionCantidad', sa.Integer(), nullable=False))
    op.add_column('pulxes', sa.Column('calificacionTotal', sa.Integer(), nullable=False))
    op.add_column('pulxes', sa.Column('password', sa.Integer(), nullable=False))
    op.drop_column('pulxes', 'calificacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulxes', sa.Column('calificacion', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('pulxes', 'password')
    op.drop_column('pulxes', 'calificacionTotal')
    op.drop_column('pulxes', 'calificacionCantidad')
    op.drop_column('pulxes', 'calificacionPromedio')
    # ### end Alembic commands ###
